language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t kurtishouser/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kurtishouser/udemy-docker-react npm run test
